-- WOW_PROJECT_ID constants
if not WOW_PROJECT_MAINLINE then
    WOW_PROJECT_MAINLINE = 1
end

if not WOW_PROJECT_CLASSIC then
    WOW_PROJECT_CLASSIC = 2
end

if not WOW_PROJECT_WOWLABS then
    WOW_PROJECT_WOWLABS = 3
end

if not WOW_PROJECT_BURNING_CRUSADE_CLASSIC then
    WOW_PROJECT_BURNING_CRUSADE_CLASSIC = 5
end

if not WOW_PROJECT_WRATH_CLASSIC then
    WOW_PROJECT_WRATH_CLASSIC = 11
end

if not WOW_PROJECT_CATACLYSM_CLASSIC then
    WOW_PROJECT_CATACLYSM_CLASSIC = 14
end

if not WOW_PROJECT_MISTS_CLASSIC then
    WOW_PROJECT_MISTS_CLASSIC = 19
end

if not WOW_PROJECT_ID then
    WOW_PROJECT_ID = WOW_PROJECT_MAINLINE
end


-- LE_EXPANSION_LEVEL constants
if not LE_EXPANSION_CLASSIC then
    LE_EXPANSION_CLASSIC = 0
end

if not LE_EXPANSION_BURNING_CRUSADE then
    LE_EXPANSION_BURNING_CRUSADE = 1
end

if not LE_EXPANSION_WRATH_OF_THE_LICH_KING then
    LE_EXPANSION_WRATH_OF_THE_LICH_KING = 2
end

if not LE_EXPANSION_CATACLYSM then
    LE_EXPANSION_CATACLYSM = 3
end

if not LE_EXPANSION_MISTS_OF_PANDARIA then
    LE_EXPANSION_MISTS_OF_PANDARIA = 4
end

if not LE_EXPANSION_WARLORDS_OF_DRAENOR then
    LE_EXPANSION_WARLORDS_OF_DRAENOR = 5
end

if not LE_EXPANSION_LEGION then
    LE_EXPANSION_LEGION = 6
end

if not LE_EXPANSION_BATTLE_FOR_AZEROTH then
    LE_EXPANSION_BATTLE_FOR_AZEROTH = 7
end

if not LE_EXPANSION_SHADOWLANDS then
    LE_EXPANSION_SHADOWLANDS = 8
end

if not LE_EXPANSION_DRAGONFLIGHT then
    LE_EXPANSION_DRAGONFLIGHT = 9
end

if not LE_EXPANSION_WAR_WITHIN then
    LE_EXPANSION_WAR_WITHIN = 10
end

if not LE_EXPANSION_LEVEL_CURRENT then
    LE_EXPANSION_LEVEL_CURRENT = LE_EXPANSION_LEGION
end